[package]
name = "marketplace-abi"

version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dependencies.marketplace]
path = ".."

[dependencies.elrond-wasm]
version = "0.18.2"
features = ["derive"]

[dependencies.elrond-wasm-debug]
version = "0.18.2"
