[EnableEpochs]
SCDeployEnableEpoch = 0
BuiltInFunctionsEnableEpoch = 0
RelayedTransactionsEnableEpoch = 0
PenalizedTooMuchGasEnableEpoch = 0
SwitchJailWaitingEnableEpoch = 0
BelowSignedThresholdEnableEpoch = 0
SwitchHysteresisForMinNodesEnableEpoch = 1
TransactionSignedWithTxHashEnableEpoch = 1
MetaProtectionEnableEpoch = 1
AheadOfTimeGasUsageEnableEpoch = 0
GasPriceModifierEnableEpoch = 0
RepairCallbackEnableEpoch = 0
BlockGasAndFeesReCheckEnableEpoch = 0
BalanceWaitingListsEnableEpoch = 0
ReturnDataToLastTransferEnableEpoch = 0
SenderInOutTransferEnableEpoch = 0
StakeEnableEpoch = 0
StakingV2EnableEpoch = 1
DoubleKeyProtectionEnableEpoch = 0
ESDTEnableEpoch = 0
GovernanceEnableEpoch = 1
DelegationManagerEnableEpoch = 1
DelegationSmartContractEnableEpoch = 1
CorrectLastUnjailedEnableEpoch = 1
RelayedTransactionsV2EnableEpoch = 2
UnbondTokensV2EnableEpoch = 1
SaveJailedAlwaysEnableEpoch = 1
ReDelegateBelowMinCheckEnableEpoch = 1
ValidatorToDelegationEnableEpoch = 1
WaitingListFixEnableEpoch = 1000000
IncrementSCRNonceInMultiTransferEnableEpoch = 0
ESDTMultiTransferEnableEpoch = 0
GlobalMintBurnDisableEpoch = 0
ESDTTransferRoleEnableEpoch = 0
BuiltInFunctionOnMetaEnableEpoch = 0
ComputeRewardCheckpointEnableEpoch = 5
SCRSizeInvariantCheckEnableEpoch = 5
BackwardCompSaveKeyValueEnableEpoch = 5
ESDTNFTCreateOnMultiShard = 0
MetaESDTSetEnableEpoch = 0
AddTokensToDelegationEnableEpoch = 0
MultiESDTTransferFixOnCallBackOnEnableEpoch = 0
OptimizeGasUsedInCrossMiniBlocksEnableEpoch = 0
CorrectFirstQueuedEpoch = 0
DeleteDelegatorAfterClaimRewardsEnableEpoch = 0
FixOOGReturnCodeEnableEpoch = 0
RemoveNonUpdatedStorageEnableEpoch = 0
OptimizeNFTStoreEnableEpoch = 3
CreateNFTThroughExecByCallerEnableEpoch = 3
StopDecreasingValidatorRatingWhenStuckEnableEpoch = 2
FrontRunningProtectionEnableEpoch = 4
DisableOldTrieStorageEpoch = 4
IsPayableBySCEnableEpoch = 3
CleanUpInformativeSCRsEnableEpoch = 3
StorageAPICostOptimizationEnableEpoch = 3
TransformToMultiShardCreateEnableEpoch = 3
ESDTRegisterAndSetAllRolesEnableEpoch = 3
ScheduledMiniBlocksEnableEpoch = 2
CorrectJailedNotUnstakedEmptyQueueEpoch = 2
DoNotReturnOldBlockInBlockchainHookEnableEpoch = 2
[[EnableEpochs.MaxNodesChangeEnableEpoch]]
EpochEnable = 0
MaxNumNodes = 36
NodesToShufflePerShard = 4

[[EnableEpochs.MaxNodesChangeEnableEpoch]]
EpochEnable = 1
MaxNumNodes = 56
NodesToShufflePerShard = 2

[GasSchedule]
[[GasSchedule.GasScheduleByEpochs]]
StartEpoch = 0
FileName = "gasScheduleV3.toml"

