[workspace]
members = [
  "marketplace",
  "marketplace/abi",
  "nft_template",
  "nft_template/abi",
  "deployer",
  "deployer/abi",
  "staking",
  "staking/abi", 
  "pay_checkout",
  "pay_checkout/meta", 
]
