[workspace]
members = [
  "marketplace",
  "marketplace/meta",
  "nft_template",
  "nft_template/meta",
  "deployer",
  "deployer/meta",
  "staking",
  "staking/meta", 
  "pay_checkout",
  "pay_checkout/meta", 
]
