[Node]
Port = "9999"
Seed = "seed"
MaximumExpectedPeerCount = 16
ThresholdMinConnectedPeers = 0

[KadDhtPeerDiscovery]
Enabled = true
Type = "optimized"
RefreshIntervalInSec = 10
ProtocolID = "/erd/kad/sandbox"
InitialPeerList = []
BucketSize = 100
RoutingTableRefreshIntervalInSec = 300

[Sharding]
TargetPeerCount = 0
MaxIntraShardValidators = 0
MaxCrossShardValidators = 0
MaxIntraShardObservers = 0
MaxCrossShardObservers = 0
MaxSeeders = 0
Type = "NilListSharder"

[AdditionalConnections]
MaxFullHistoryObservers = 0
