[package]
name = "nft_template-abi"

version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dependencies.nft_template]
path = ".."

[dependencies.elrond-wasm]
version = "0.28.0"

[dependencies.elrond-wasm-debug]
version = "0.28.0"
