[[Observers]]
ShardId = 0
Address = "http://localhost:10100"
Type = "Validator"

[[Observers]]
ShardId = 4294967295
Address = "http://localhost:10101"
Type = "Validator"

[[FullHistoryNodes]]
ShardId = 0
Address = "http://localhost:10100"
Type = "Validator"

[[FullHistoryNodes]]
ShardId = 4294967295
Address = "http://localhost:10101"
Type = "Validator"

[GeneralSettings]
ServerPort = 7950
RequestTimeoutSec = 80
HeartbeatCacheValidityDurationSec = 25
ValStatsCacheValidityDurationSec = 60
EconomicsMetricsCacheValidityDurationSec = 600
BalancedObservers = true
BalancedFullHistoryNodes = true
FaucetValue = "0"
RateLimitWindowDurationSeconds = 60

[AddressPubkeyConverter]
Length = 32
Type = "bech32"

[Marshalizer]
Type = "gogo protobuf"

[Hasher]
Type = "blake2b"

[ApiLogging]
LoggingEnabled = false
ThresholdInMicroSeconds = 10000
