[package]
name = "pay_checkout"
version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[lib]
path = "src/libs.rs"

[features]
wasm-output-mode = [ "elrond-wasm-node"]

[dependencies.marketplace]
path="../marketplace"

[dependencies.elrond-wasm]
version = "0.31.1"

[dependencies.elrond-wasm-derive]
version = "0.31.1"

[dependencies.elrond-wasm-node]
version = "0.31.1"
optional = true

[dev-dependencies.elrond-wasm-debug]
version = "0.31.1"
