[Node]
Port = "21500"
Seed = ""
ThresholdMinConnectedPeers = 1

[KadDhtPeerDiscovery]
Enabled = true
Type = "optimized"
RefreshIntervalInSec = 10
ProtocolID = "/erd/kad/sandbox"
InitialPeerList = [ "/ip4/127.0.0.1/tcp/9999/p2p/16Uiu2HAkw5SNNtSvH1zJiQ6Gc3WoGNSxiyNueRKe6fuAuh57G3Bk",]
BucketSize = 100
RoutingTableRefreshIntervalInSec = 300

[Sharding]
TargetPeerCount = 36
MaxIntraShardValidators = 7
MaxCrossShardValidators = 15
MaxIntraShardObservers = 2
MaxCrossShardObservers = 3
MaxSeeders = 2
Type = "NilListSharder"

[AdditionalConnections]
MaxFullHistoryObservers = 10
